In [1]:

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import warnings

import warnings
warnings.filterwarnings("ignore")

In [2]:
list_500 = list(pd.read_html('https://en.wikipedia.org/wiki/NIFTY_500')[2][3])
list_50 = list(pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[1]['Symbol'])

In [3]:
stock_universe = list_50

In [8]:
start_date = '2024-12-23'
end_date = datetime.now().strftime('%Y-%m-%d')
country_code = ".NS"

valid_stock_array = []
for i in range(1, len(stock_universe)):
    stock_ticker = stock_universe[i] + country_code
    valid_stock_array.append(stock_ticker)

df = yf.download(valid_stock_array, start=start_date, end=end_date, interval = '1d')

[*********************100%***********************]  49 of 49 completed

In [ ]:
df['']

Price                         Adj Close                              \
Ticker                    ADANIPORTS.NS APOLLOHOSP.NS ASIANPAINT.NS
Date
2024-12-23 00:00:00+00:00   1191.800049   7265.100098   2279.199951
2024-12-24 00:00:00+00:00   1182.199951   7240.000000   2284.000000
2024-12-26 00:00:00+00:00   1243.949951   7261.149902   2262.399902
2024-12-27 00:00:00+00:00   1230.699951   7246.299805   2271.399902
2024-12-30 00:00:00+00:00   1218.500000   7314.250000   2288.250000

Price                                                               \
Ticker                     AXISBANK.NS BAJAJ-AUTO.NS BAJAJFINSV.NS
Date
2024-12-23 00:00:00+00:00  1079.150024   8768.450195   1563.400024
2024-12-24 00:00:00+00:00  1078.900024   8778.049805   1564.550049
2024-12-26 00:00:00+00:00  1076.699951   8878.500000   1559.300049
2024-12-27 00:00:00+00:00  1077.449951   8928.299805   1579.300049
2024-12-30 00:00:00+00:00  1069.949951   8779.900391   1576.699951

Price                                                                          \
Ticker                    BAJFINANCE.NS      BEL.NS BHARTIARTL.NS     BPCL.NS
Date
2024-12-23 00:00:00+00:00   6866.700195  294.350006   1586.900024  289.100006
2024-12-24 00:00:00+00:00   6808.200195  292.450012   1583.900024  292.000000
2024-12-26 00:00:00+00:00   6815.750000  295.200012   1599.500000  295.600006
2024-12-27 00:00:00+00:00   6907.750000  292.049988   1599.849976  293.549988
2024-12-30 00:00:00+00:00   6888.250000  284.899994   1586.900024  293.299988

Price                      ...       Volume                              \
Ticker                     ... SUNPHARMA.NS TATACONSUM.NS TATAMOTORS.NS
Date                       ...
2024-12-23 00:00:00+00:00  ...      1299181       1054695       9653868
2024-12-24 00:00:00+00:00  ...      1121058       1038280      12553555
2024-12-26 00:00:00+00:00  ...      1402706        595956       9343210
2024-12-27 00:00:00+00:00  ...      1668898        870974      15835079
2024-12-30 00:00:00+00:00  ...      6021550       1830048      17441198

Price                                                                       \
Ticker                    TATASTEEL.NS   TCS.NS TECHM.NS TITAN.NS TRENT.NS
Date
2024-12-23 00:00:00+00:00     27514178  2195338  1301223   691202   783189
2024-12-24 00:00:00+00:00     25882917  1181886   711026   485245   486797
2024-12-26 00:00:00+00:00     23939932  1208464   659638   637094   440974
2024-12-27 00:00:00+00:00     19562177   858100   647945   568989   530288
2024-12-30 00:00:00+00:00     32555723  1527169  6781500   941859   960856

Price
Ticker                    ULTRACEMCO.NS  WIPRO.NS
Date
2024-12-23 00:00:00+00:00        149350   6693583
2024-12-24 00:00:00+00:00        108000   8837902
2024-12-26 00:00:00+00:00        144283   6516148
2024-12-27 00:00:00+00:00        118410   8063921
2024-12-30 00:00:00+00:00        164726  13709891

[5 rows x 294 columns]

In [10]:
max_pct_return = float(0)
max_pct_stock = ''


max_array = []
for symbol in valid_stock_array:
    init_price = df['Open'][symbol].iloc[0]
    final_price = df['Close'][symbol].iloc[len(df) - 1]

    weekly_pct = (final_price - init_price) / init_price

    if weekly_pct > max_pct_return:
        max_pct_return = weekly_pct
        max_pct_stock = symbol
    
    max_array.append([weekly_pct, symbol])

In [11]:
max_array

[[0.023992646749561707, 'ADANIPORTS.NS'],
 [0.00870900987343448, 'APOLLOHOSP.NS'],
 [-0.005108695652173913, 'ASIANPAINT.NS'],
 [-0.00479027488699895, 'AXISBANK.NS'],
 [-0.007915276712472672, 'BAJAJ-AUTO.NS'],
 [-0.0012686675366101203, 'BAJFINANCE.NS'],
 [-0.003979816063250158, 'BAJAJFINSV.NS'],
 [-0.03095240171263818, 'BEL.NS'],
 [0.0044520129896190065, 'BPCL.NS'],
 [0.0005674807150457125, 'BHARTIARTL.NS'],
 [0.020074430459617428, 'BRITANNIA.NS'],
 [0.03219245891250375, 'CIPLA.NS'],
 [-0.02098447177076587, 'COALINDIA.NS'],
 [0.010939812345126651, 'DRREDDY.NS'],
 [0.022273643092105264, 'EICHERMOT.NS'],
 [-0.02091595632213885, 'GRASIM.NS'],
 [0.005446938322582747, 'HCLTECH.NS'],
 [-0.002300771933747194, 'HDFCBANK.NS'],
 [-0.012238962528289973, 'HDFCLIFE.NS'],
 [-0.04064144383591065, 'HEROMOTOCO.NS'],
 [-0.039085624944689784, 'HINDALCO.NS'],
 [0.0027813436029097134, 'HINDUNILVR.NS'],
 [0.0, 'ICICIBANK.NS'],
 [0.026146213828000534, 'INDUSINDBK.NS'],
 [-0.012460842060923523, 'INFY.NS'],
 [0.012308972077064396, 'ITC.NS'],
 [-0.03958332029163328, 'JSWSTEEL.NS'],
 [-0.0038913011891988556, 'KOTAKBANK.NS'],
 [-0.024809277609843323, 'LT.NS'],
 [0.029095237266535297, 'M&M.NS'],
 [-0.011809096329383236, 'MARUTI.NS'],
 [-0.0046544228830645165, 'NESTLEIND.NS'],
 [-0.013396844542327627, 'NTPC.NS'],
 [-0.023504747548858868, 'ONGC.NS'],
 [-0.03286167360701651, 'POWERGRID.NS'],
 [-0.003539134837962963, 'RELIANCE.NS'],
 [0.0023204341401193945, 'SBILIFE.NS'],
 [0.004473503097040606, 'SHRIRAMFIN.NS'],
 [-0.03548268742583907, 'SBIN.NS'],
 [0.04025401679407096, 'SUNPHARMA.NS'],
 [-0.009821312107766579, 'TCS.NS'],
 [0.009553592576510136, 'TATACONSUM.NS'],
 [-6.813110554323492e-05, 'TATAMOTORS.NS'],
 [-0.039101384238382886, 'TATASTEEL.NS'],
 [0.0295404520969144, 'TECHM.NS'],
 [-0.03574494435016216, 'TITAN.NS'],
 [0.012278034593340611, 'TRENT.NS'],
 [-0.020108540852864582, 'ULTRACEMCO.NS'],
 [-0.009458557856340246, 'WIPRO.NS']]